
###############################################################################################
#                                                                                             #
#   WWWWWWW# WWWWWW- =WW@         #WWWWWW*  =WWWWWW  #WW:      -#WWWWW@- *WWWWWWWW: WWWWWWW   #
#   WWW:-::   @WW*   =WW@         #WW#:#WW=   WWW*   #WW:      #WW#-#WW@ -:-@WW=-:- WWW+--:   #
#   WWW-      @WW*   =WW@         #WW= *WW=   WWW*   #WW:      @WW= *WW@    @WW=   -WWW:      #
#   WWW*+++-  @WW*   =WW@         #WW#=WWW=   WWW*   #WW:      @WW= *WW@    @WW=   *WWW=+++   #
#   WWWWWWW-  @WW*   =WW@:WW=     #WWWWW+     WWW*   #WW: :WW  @WW= *WW@    @WW=   *WWWWWWW   #
#   WWW-      @WW=-  =WW@*WW#     #WW#       -WWW*-  #WW; ;WW  #WW@:#WW@    @WW=  -*WWW*,__   #
#   WWW-    :WWWWWW- =WWWWWW@     #WW=      +WWWWWW  #WWWWWWW.  =WWWWW#     @WW=  -*WWWWWWW   #
#                                                                                             #
###############################################################################################

substitutions:
  name: 'fil_pilote'
  
  uart_esp_0_baudrate: '1200'  # Pour option Linky : #1200 en mode historique >> #9600 en mode standard
  
esphome:
  name: ${name}
  comment: 'Gestion du chauffage par fil pilote et communication Linky.'
  area: 'Local Technique'
  project:
    name: dackara.${name}
    version: "1.0"

# https://esphome.io/components/esp32.html
esp32:
  board: 'esp32-s3-devkitc-1' #'esp32dev'
  framework:
    type: 'arduino' #'esp-idf'
    version: '2.0.14' #'2.0.11'
    platform_version: '6.5.0'  #'6.4.0'

# Captive Portal: https://esphome.io/components/captive_portal.html
captive_portal:

# Logger Component: https://esphome.io/components/logger.html
logger:

# Native API Component: https://esphome.io/components/api.html
api:

# OTA Update Component: https://esphome.io/components/ota.html
ota:

# Web Server: https://esphome.io/components/web_server.html
web_server:
  port: 80

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://dackara/fil_pilote/software_esphome/fil_pilote.yaml@main
  import_full_config: false #true

# WiFi Component: https://esphome.io/components/wifi.html
wifi:
  ap:
    ssid: 'Espilote Fallback Hotspot'

# Configuring Wi-Fi on an ESP32 device by using Bluetooth
esp32_improv:
  authorizer: none

# Sets up the improv via serial client for Wi-Fi provisioning
improv_serial:

# https://esphome.io/guides/configuration-types#packages
packages:
  device_base: !include packages/base/device_base.yaml

  # Déclaration des zones de chauffe piloté :
  fil_pilote_zone_1: !include
    file: packages/fil_pilote/device_fp_zone.yaml
    vars:
      fpilote_id: chauffage_zone_1
      fpilote_mode: 'mode'
      fpilote_pos_pin: '0'
      fpilote_neg_pin: '1'
      fpilote_hub: sx1509_hub0

  fil_pilote_zone_2: !include
    file: packages/fil_pilote/device_fp_zone.yaml
    vars:
      fpilote_id: chauffage_zone_2
      fpilote_mode: 'mode'
      fpilote_pos_pin: '2'
      fpilote_neg_pin: '3'
      fpilote_hub: sx1509_hub0
      
  fil_pilote_zone_3: !include
    file: packages/fil_pilote/device_fp_zone.yaml
    vars:
      fpilote_id: chauffage_zone_3
      fpilote_mode: 'mode'
      fpilote_pos_pin: '4'
      fpilote_neg_pin: '5'
      fpilote_hub: sx1509_hub0
      
  fil_pilote_zone_4: !include
    file: packages/fil_pilote/device_fp_zone.yaml
    vars:
      fpilote_id: chauffage_zone_4
      fpilote_mode: 'mode'
      fpilote_pos_pin: '6'
      fpilote_neg_pin: '7'
      fpilote_hub: sx1509_hub0

###################################################
#         A supprimer si seulement 4 zones        #
###################################################
#                        I                        #
#                       \_/                       #
#                        *                        #
  fil_pilote_zone_5: !include                     #
    file: packages/fil_pilote/device_fp_zone.yaml #
    vars:                                         #
      fpilote_id: chauffage_zone_5                #
      fpilote_mode: 'mode'                        #
      fpilote_pos_pin: '9'                        #
      fpilote_neg_pin: '8'                        #
      fpilote_hub: sx1509_hub0                    #
#                                                 #
  fil_pilote_zone_6: !include                     #
    file: packages/fil_pilote/device_fp_zone.yaml #
    vars:                                         #
      fpilote_id: chauffage_zone_6                #
      fpilote_mode: 'mode'                        #
      fpilote_pos_pin: '11'                       #
      fpilote_neg_pin: '10'                       #
      fpilote_hub: sx1509_hub0                    #
#                                                 #
  fil_pilote_zone_7: !include                     #
    file: packages/fil_pilote/device_fp_zone.yaml #
    vars:                                         #
      fpilote_id: chauffage_zone_7                #
      fpilote_mode: 'mode'                        #
      fpilote_pos_pin: '13'                       #
      fpilote_neg_pin: '12'                       #
      fpilote_hub: sx1509_hub0                    #
#                                                 #
  fil_pilote_zone_8: !include                     #
    file: packages/fil_pilote/device_fp_zone.yaml #
    vars:                                         #
      fpilote_id: chauffage_zone_8                #
      fpilote_mode: 'mode'                        #
      fpilote_pos_pin: '15'                       #
      fpilote_neg_pin: '14'                       #
      fpilote_hub: sx1509_hub0                    #
#                                                 #
###################################################

  # Déclaration du module TéléInfo Client
  teleinfo: !include 
    file: packages/teleinfo/historique.yaml      # Si compteur en mode "Historique"
#    file: packages/teleinfo/standard.yaml       # Si compteur en mode "Standard"
    vars:
      linky_name: 'myteleinfo'
      linky_uartid: uart_esp_0
      linky_update_interval: '5s'