
###############################################################################################
#                                                                                             #
#   WWWWWWW# WWWWWW- =WW@         #WWWWWW*  =WWWWWW  #WW:      -#WWWWW@- *WWWWWWWW: WWWWWWW   #
#   WWW:-::   @WW*   =WW@         #WW#:#WW=   WWW*   #WW:      #WW#-#WW@ -:-@WW=-:- WWW+--:   #
#   WWW-      @WW*   =WW@         #WW= *WW=   WWW*   #WW:      @WW= *WW@    @WW=   -WWW:      #
#   WWW*+++-  @WW*   =WW@         #WW#=WWW=   WWW*   #WW:      @WW= *WW@    @WW=   *WWW=+++   #
#   WWWWWWW-  @WW*   =WW@:WW=     #WWWWW+     WWW*   #WW: :WW  @WW= *WW@    @WW=   *WWWWWWW   #
#   WWW-      @WW=-  =WW@*WW#     #WW#       -WWW*-  #WW; ;WW  #WW@:#WW@    @WW=  -*WWW*,__   #
#   WWW-    :WWWWWW- =WWWWWW@     #WW=      +WWWWWW  #WWWWWWW.  =WWWWW#     @WW=  -*WWWWWWW   #
#                                                                                             #
###############################################################################################

substitutions:
  node_name: 'fil_pilote'
  name: 'Fil Pilote'
  comment: 'Gestion du chauffage par fil pilote et communication Linky.'
  area: 'Local Technique'
  
  board: 'esp32-s3-devkitc-1' #'esp32dev'
  framework_type: 'arduino' #'esp-idf'
  framework_version: 2.0.14 #'2.0.11' #'2.0.5' #'2.0.9'
  platform_version: '6.5.0'  #'6.4.0' #'4.4.0' #'6.2.0'
  
  # ID du SX1509
  sx1509_fp_bus: 'bus_sx1509_fp' 
  # ID du bus I2C
  i2c_id_fp_bus: 'bus_i2c_fp' 
  
# https://esphome.io/guides/configuration-types#packages
packages:
  wifi: !include 
    file: packages/wifi.yaml
    vars:
      ssid: !secret esphome_ssid
      password: !secret esphome_password
      power_save_mode: 'none'  #'none' #'light' #'hight'
      static_ip: '192.168.0.174' # '192.168.0.21'
      gateway: '192.168.0.109'
      subnet: '255.255.255.0'
      ap_ssid: 'Espilote Fallback Hotspot'
  device_base: !include packages/device_base.yaml
  
  # Déclaration du bus I2C et du composant SX1509 :
  fp_sx1509: !include
    file: packages/fil-pilote/sx1509.yaml
    vars:
      sx1509_fp: ${sx1509_fp_bus}
      sx1509_address_fp: '0x3E' #'0x3F' #'0x70' #'0x71'
      i2c_id_fp: ${i2c_id_fp_bus}
  fp_i2c: !include
    file: packages/fil-pilote/i2c.yaml
    vars:
      i2c_id_fp: ${i2c_id_fp_bus}
      i2c_sda_fp: 'GPIO8'
      i2c_scl_fp: 'GPIO9'
      i2c_frequency: '50kHz'

  # Déclaration des zones de chauffe piloté :
  fil_pilote_zone_1: !include
    file: packages/fil-pilote/fil-pilote.yaml
    vars:
      fp1_id: 'fp1'
      fp1_name: 'Zone 1'
      fp1_pos_gpio: '0'
      fp1_neg_gpio: '1'
      sx1509_fp: ${sx1509_fp_bus}

  fil_pilote_zone_2: !include
    file: packages/fil-pilote/fil-pilote.yaml
    vars:
      fp1_id: 'fp2'
      fp1_name: 'Zone 2'
      fp1_pos_gpio: '2'
      fp1_neg_gpio: '3'
      sx1509_fp: ${sx1509_fp_bus}
      
  fil_pilote_zone_3: !include
    file: packages/fil-pilote/fil-pilote.yaml
    vars:
      fp1_id: 'fp3'
      fp1_name: 'Zone 3'
      fp1_pos_gpio: '4'
      fp1_neg_gpio: '5'
      sx1509_fp: ${sx1509_fp_bus}
      
  fil_pilote_zone_4: !include
    file: packages/fil-pilote/fil-pilote.yaml
    vars:
      fp1_id: 'fp4'
      fp1_name: 'Zone 4'
      fp1_pos_gpio: '6'
      fp1_neg_gpio: '7'
      sx1509_fp: ${sx1509_fp_bus}

###############################################
#       A supprimer si seulement 4 zones      #
###############################################
#                      I                      #
#                     \_/                     #
#                      *                      #
  fil_pilote_zone_5: !include                 #
    file: packages/fil-pilote/fil-pilote.yaml #
    vars:                                     #
      fp1_id: 'fp5'                           #
      fp1_name: 'Zone 5'                      #
      fp1_pos_gpio: '8'                       #
      fp1_neg_gpio: '9'                       #
      sx1509_fp: ${sx1509_fp_bus}             #
#                                             #
  fil_pilote_zone_6: !include                 #
    file: packages/fil-pilote/fil-pilote.yaml #
    vars:                                     #
      fp1_id: 'fp6'                           #
      fp1_name: 'Zone 6'                      #
      fp1_pos_gpio: '10'                      #
      fp1_neg_gpio: '11'                      #
      sx1509_fp: ${sx1509_fp_bus}             #
#                                             #
  fil_pilote_zone_7: !include                 #
    file: packages/fil-pilote/fil-pilote.yaml #
    vars:                                     #
      fp1_id: 'fp7'                           #
      fp1_name: 'Zone 7'                      #
      fp1_pos_gpio: '12'                      #
      fp1_neg_gpio: '13'                      #
      sx1509_fp: ${sx1509_fp_bus}             #
#                                             #
  fil_pilote_zone_8: !include                 #
    file: packages/fil-pilote/fil-pilote.yaml #
    vars:                                     #
      fp1_id: 'fp8'                           #
      fp1_name: 'Zone 8'                      #
      fp1_pos_gpio: '14'                      #
      fp1_neg_gpio: '15'                      #
      sx1509_fp: ${sx1509_fp_bus}             #
#                                             #
###############################################

  # Déclaration du module TéléInfo Client
  teleinfo: !include 
    file: packages/teleinfo/historique.yaml     # Si compteur en mode Historique
#    file: packages/teleinfo/standard.yaml      # Si compteur en mode Standard
    vars:
      linky_name: 'Linky'
      tic_id: 'myteleinfo'
      tic_uart_id: 'tic_uart_bus'
      tic_rx_pin: 'GPIO3'
      tic_tx_pin: 'GPIO1'
      tic_update_interval: '5s'
